name: Master

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - run: bun i
      #- run: git config --global user.email "bolanosDev-ci@github.com"
      #- run: git config --global user.name "BolanosDev ci"
      #- run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >.npmrc
      #- run: echo "@phoenix_ui:registry=https://registry.npmjs.org/" >>.npmrc
      #- run: echo "always-auth=true" >>.npmrc
      #- run: cat .npmrc
      - run: git reset --hard
      - run: bun run patch
      #- run: ls -la
      #- run: git status
      #- run: lerna version patch --no-git-tag-version -y
      #- run: git add . && git commit -m "bump versions"
      #- run: lerna publish from-package -y
      #- run: ls -la
      #- run: git status
