name: pull request
on:
  pull_request:
    types: [opened, synchronize]

env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - run: bun i
      - run: git branch --track main origin/main
      - run: bun run lint
      - run: bun run test
  changeset:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Changeset
        uses: generates/changeset-action@v3.0.0
      - name: Commit Changes
        uses: generates/commit-action@v1.0.1
        with:
          token: ${{ secrets.BDEV_GITHUB_TOKEN }}
